codereview
KotenkoNata/Front-end_School_HW_1 pull request #1
Opened 2021-12-21 20:09 UTC by KotenkoNata

2021-12-22 12:35 UTC, radoshDev requested changes

2021-12-22 12:35 UTC, radoshDev commented on src/components/AppBar/AppBar.js
> +    <header>
В тебе `<header>` тут і в **Navigation** дублюється.

2021-12-22 12:35 UTC, radoshDev commented on src/components/Section/Section.module.css
> +}
Чи потрібен цей файл?

2021-12-22 12:35 UTC, radoshDev commented on src/views/UserView/UserView.js
> +        <UserProfile key={userDetails.data.id} name={name} userDetails={userDetails.data} />
А для чого тут атрибут `key`?

2021-12-22 12:35 UTC, radoshDev commented on src/views/UserView/UserView.js
> +  }, []);
Це і отримання **UserDetails** можна винести в окремий кастомний хук

2021-12-22 12:35 UTC, radoshDev commented on src/views/HomePage/HomeView.js
> +  }, []);
Можна винести в окремий кастомний хук

2021-12-22 12:35 UTC, radoshDev commented on src/nFormatter.js
> +function nFormatter(number_) {
А що означає "_" в назві параметру `number_`?

2021-12-22 12:35 UTC, radoshDev commented on src/components/UserProfile/UserProfile.js
> +    <div className={style["main-container"]}>
На проєкті для значення атрибуту className ти використовуєш dot notation (`style.name`), а в цьому файлі bracket notation (`style['name']`)

2021-12-22 12:35 UTC, radoshDev commented on src/components/VideoListItem/VideoListItem.js
> +    </li>
На мою думку, дуже великий компонент, його можна розділити на менші

2021-12-23 13:03 UTC, KotenkoNata commented on src/views/UserView/UserView.js
> +        <UserProfile key={userDetails.data.id} name={name} userDetails={userDetails.data} />
```suggestion
        <UserProfile name={name} userDetails={userDetails.data} />
```

2021-12-23 13:05 UTC, KotenkoNata commented on src/views/UserView/UserView.js
> +  }, []);
Що ти маєш на у вазі? Який кастомний хук? Об'єднати два запити у один? Можна приклад?

2021-12-23 13:05 UTC, KotenkoNata commented on src/views/HomePage/HomeView.js
> +  }, []);
Що ти маєш на у вазі? Який кастомний хук? Об'єднати два запити у один? Можна приклад?

2021-12-23 13:06 UTC, KotenkoNata commented on src/components/VideoListItem/VideoListItem.js
> +    </li>
ок, подумаю як можна зробити

2021-12-23 14:02 UTC, KotenkoNata commented on src/components/AppBar/AppBar.js
> +    <header>
Виправила

2021-12-23 14:02 UTC, KotenkoNata commented on src/components/Section/Section.module.css
> +}
Видалила

2021-12-23 14:03 UTC, KotenkoNata commented on src/nFormatter.js
> +function nFormatter(number_) {
виправила

2021-12-23 14:03 UTC, KotenkoNata commented on src/components/VideoListItem/VideoListItem.js
> +    </li>
Виправила. Подивись чи так ок?

2021-12-23 15:15 UTC, VolodymyrSi requested changes
Дуже кльовий код, мені сподобалось читати. Все суууууперструктуровано :)

2021-12-23 15:15 UTC, VolodymyrSi commented on src/App.js
> +      <Suspense fallback={<Loading />}>
Бачу що це експерементальна фіча, як думаєш, можливо варто в документації про це згадати, чи залишити про це коментар в коді? (другий варіант мені не дуже подобається)

2021-12-23 15:15 UTC, VolodymyrSi commented on src/App.js
> +        <Switch>
Зараз вже є версія роутеру 6, у ній замість `Switch` `Routes`, а `exact` це дефолтна поведінка. Можливо також варто про це згадати в документації, щоб розробникам які будуть підтримувати проект було простіше працювати з кодом? у форматі _router v6 is now available, please review the documentation before updating to it_ не знаю, як правильно працюють у випадках роботи з попередніми версіями пакетів :)

2021-12-23 15:15 UTC, VolodymyrSi commented on src/App.js
> +import NotFound from "./views/NotFound";
Що ти думаєш про те, щоб назвати папку **pages**, оскільки це дійсно 'сторінки' які повертає react router? На мій смак назва views трішки не те значення передає

2021-12-23 15:15 UTC, VolodymyrSi commented on src/components/AppBar/AppBar.js
> +import React from "react";
я бачу що ти імпортуєш реакт у кожній компоненті, здається, у сучасних версіях реакту у цьому немає потреби. Можливо, видалити ці імпорти?

2021-12-23 15:15 UTC, VolodymyrSi commented on src/components/AppBar/AppBar.js
> +  return <Navigation />;
`AppBar` повертає те ж саме, що і компонент `Navigation`. Була ідея додавати щось ще у `AppBar`? Якщо ні, я думаю можна позбутись цього компоненту і рендерити лише навігацію (якщо це не якийсь стильовий контейнер) :) А якщо стильовий, то можливо зробити його div-ом, а не реакт компонентом?

2021-12-23 15:15 UTC, VolodymyrSi commented on src/components/AppBar/index.js
> +export { default } from "./AppBar";
а можеш будь-ласка скинути щось почитати на тему цього рішення? я правильно розумію, що це для того, щоб потім імпортувати по назві папки, з автоматичним підтягненням файлу, а не імпортувати з конкретного файлу?

2021-12-23 15:15 UTC, VolodymyrSi commented on src/components/Button/Button.module.css
> +  border: none;
Як щодо групування **css**?
[Сss grouping](https://css-tricks.com/poll-results-how-do-you-order-your-css-properties/)

Наприклад `border / border-radius` можуть бути поруч. Я бачу що багато схожих властивостей вже згруповані)

Можна також ієрархічно групувати, де розміри елементу будуть зверху, а шрифти - знизу. 
Не обов"язково щось міняти тут, просто хотілось сказати)

2021-12-23 15:15 UTC, VolodymyrSi commented on src/components/Container/Container.module.css
> +.Container {
перед цим класи були переважно з маленької літери, є причина чому тут велика?

2021-12-23 15:15 UTC, VolodymyrSi commented on src/components/Navigation/Navigation.module.css
> +  text-decoration: none;
те про що я писав трішки вище, можливо є сенс починати з display: `flex`, і закінчувати `text-decoration`, щоб з розростанням **css** він легко читався від більш важливих до менш важливих _(якщо це можна назвати важливістю)_ атрибутів

2021-12-23 15:15 UTC, VolodymyrSi commented on src/components/VideoListItem/VideoListItem.js
> +import style from "./VideoListItem.module.css";
зазвичай ти імпортувала стилі перед компонентами

2021-12-23 15:15 UTC, VolodymyrSi commented on src/index.css
> +* Styles for the Loader
Думаєш, назва класу не передає, про що цей селектор? :)

2021-12-23 15:15 UTC, VolodymyrSi commented on src/nFormatter.js
> +function nFormatter(number) {
я до цього моменту в коді думав, що це буде за функція)
Можливо назвати її numberFormatter? 
мені здається, NumberFormatter (num) (якщо ідея в тому щоб не використовувати number двічі - в назві і як аргумент), може бути більш зрозуміло для тих хто читає код вперше)

2021-12-23 15:47 UTC, radoshDev commented on src/views/UserView/UserView.js
> +  }, []);
Хук - це ж простими словами функція, яка виконує якусь логіку і щось нам повертає, просто в назві префікс **use**. Наприклад, створюємо файл useFetchTrendVideo.js, в ньому називаємо так і сам хук. Цю логіку яку я виділив виносимо в цей файл.
```suggestion
export const useFetchTrendVideo = () => {

	const [trendingVideos, setTrendingVideos] = useState({
		data: [],
		error: "",
		loading: true,
	})

	useEffect(() => {
		async function innerFunction() {
			try {
				const response = await fetchTrendingVideo()
				setTrendingVideos(() => ({
					data: response.data,
					error: "",
					loading: false,
				}))
			} catch (error) {
				setTrendingVideos(() => ({
					data: [],
					error: error.message,
					loading: false,
				}))
			}
		}

		Logger.trace(innerFunction())
	}, [])

	return trendingVideos
}
```

2021-12-23 15:54 UTC, radoshDev commented on src/views/UserView/UserView.js
> +  }, []);
Відповідно потрібно зробити всі необхідні імпорти. Далі у файлі **UserView.js** ти використовуєш цей хук як звичайний `useState`.

`const trendingVideos = useFetchTrendVideo() `

Але ти можеш піти ще далі та спробувати всі axios запити об'єднати в один хук.

2021-12-23 18:38 UTC, KotenkoNata commented on src/App.js
> +      <Suspense fallback={<Loading />}>
Дякую за комент, але трохи не розумію навіщо. Треба було писати документацію? Думаю коментар писати не треба, так як є документація до самого елемента.

2021-12-23 18:39 UTC, KotenkoNata commented on src/App.js
> +        <Switch>
Дякую за комент, але це більше відноситься до версії фреімворку, а не до самого коду. Я з новив роутером не працювала, тому обрала попередній з яким є досвід :)

2021-12-23 18:43 UTC, KotenkoNata commented on src/components/AppBar/AppBar.js
> +import React from "react";
Це пов'язано з налаштуванням `eslint`. Якщо в файлі є `import React ...` то цей файл аналізуюється як JSX, навіть якщо розширення файлу `.js`. 

<img width="623" alt="Screenshot 2021-12-23 at 20 28 02" src="https://user-images.githubusercontent.com/35960689/147279278-9820758e-e241-4b32-9f2d-13985b12bec6.png">

2021-12-23 18:46 UTC, KotenkoNata commented on src/components/VideoListItem/VideoListItem.js
> +import style from "./VideoListItem.module.css";
Здається є якась вимога, щоб імпорт стилів був після імпорту `PropTypes` або `React`. EsLint про це казав. А взагалі, наскільки мені відомо, сортування імпортів не критично :)

2021-12-23 18:47 UTC, KotenkoNata commented on src/index.css
> +* Styles for the Loader
Ти має на увазі що коментар зайвий тут?

2021-12-23 19:25 UTC, KotenkoNata commented on src/App.js
> +import NotFound from "./views/NotFound";
Дякую за комент. `views` та `pages` це слова синоніми. Якщо це критично, то я можу змінити назву директорії. Це критично?

2021-12-23 19:26 UTC, KotenkoNata commented on src/views/UserView/UserView.js
> +  }, []);
Готово

2021-12-23 19:30 UTC, VolodymyrSi commented on src/App.js
> +      <Suspense fallback={<Loading />}>
Якщо ти пам"ятаєш, на одній з лекцій хтось коментував наші роботи, і казав що були роботи з дуже крутими рідмі файлами, де було вказано яку версію ноди треба, щоб запустити проект, і таке інше. Мені здається, це маленька але хороша деталь, яка могла б полегшити життя майбутнім розробникам, якби була пристутньою якимось із пунктів у рідмі

2021-12-23 19:31 UTC, VolodymyrSi commented on src/App.js
> +        <Switch>
Тут те ж саме що і до експерементальної фічі, звичайно це не може бути обов"язковою вимогою, але кльовий ворнінг, типу "якщо ви вирішите оновити реакт роутер, майте на увазі що усе зламається :)

2021-12-23 19:31 UTC, KotenkoNata commented on src/components/AppBar/AppBar.js
> +  return <Navigation />;
Дякую за коментар, виправила

2021-12-23 19:32 UTC, KotenkoNata commented on src/components/AppBar/index.js
> +export { default } from "./AppBar";
Де почитати - не знаю. Нас так вчили на курсі по React :)

2021-12-23 19:34 UTC, VolodymyrSi commented on src/App.js
> +import NotFound from "./views/NotFound";
Жоден з моїх коментарів не є критичним, бо у мене немає достатньої експертизи, щоб залишати "критичні" коментарі. Практика критерій істини, і якщо написаний код працює як очікувалось, то всі мої коментарі то лише побажання і думки)

Views та pages можливо і є синонімами в якомусь контексті, не буду переводити це на якісь лінгвістичні дискусії)

Pages це також не назвеш, бо там є елементи у папці, що не є сторінками. Залишаю на твій розсуд, як тобі здається більш правильним, це твій проект

2021-12-23 19:34 UTC, KotenkoNata commented on src/components/Button/Button.module.css
> +  border: none;
Дякую за коментар, це буде дуже корисно :)

2021-12-23 19:35 UTC, VolodymyrSi commented on src/components/VideoListItem/VideoListItem.js
> +import style from "./VideoListItem.module.css";
просто було б класно завжди тримати все в однаковому порядку, воно тоді прям ух, як красиво)

2021-12-23 19:35 UTC, VolodymyrSi commented on src/index.css
> +* Styles for the Loader
назва класу .loader настільки ідеально підібрана, що описувати його як "стилі для лоадера" немає потреби, як на мене

2021-12-23 19:36 UTC, KotenkoNata commented on src/components/Container/Container.module.css
> +.Container {
Виправила

2021-12-23 19:37 UTC, KotenkoNata commented on src/nFormatter.js
> +function nFormatter(number) {
Виправила

2021-12-23 19:43 UTC, KotenkoNata commented on src/App.js
> +import NotFound from "./views/NotFound";
Добре, дякую :)

2021-12-23 19:46 UTC, KotenkoNata commented on src/App.js
> +        <Switch>
Так, але мені здається, це повинно бути зроблено на боці `eslint`, а не через коментар у коді, тому що він може писати ворнінги в логи. В книзі Clean Code пишуть що коменти в коді це зло :)

2021-12-23 19:48 UTC, KotenkoNata commented on src/index.css
> +* Styles for the Loader
Видалила

2021-12-23 19:57 UTC, KotenkoNata commented on src/App.js
> +      <Suspense fallback={<Loading />}>
Усі версії вказані у pacakge.json, нема сенсу писати те саме ще і у readme.
Щодо використання експериментальної фічі, це вже відноситься до повноцінної документації.

2021-12-23 19:57 UTC, KotenkoNata commented on src/components/Navigation/Navigation.module.css
> +  text-decoration: none;
Добре, дякую :)

2021-12-27 13:15 UTC, radoshDev commented on src/components/UserProfile/UserProfileStatistics.js
> +      <UserProfileStatisticItem count={heartCount} name={names.likes} />
Тут можна map використати

2021-12-27 13:50 UTC, KotenkoNata commented on src/components/UserProfile/UserProfileStatistics.js
> +      <UserProfileStatisticItem count={heartCount} name={names.likes} />
Яким чином? Тут немає масиву.

2021-12-27 14:09 UTC, radoshDev commented on src/components/UserProfile/UserProfileStatistics.js
> +      <UserProfileStatisticItem count={heartCount} name={names.likes} />
Ну виправлене краще)

2021-12-27 14:17 UTC, KotenkoNata commented
@radoshDev, @VolodymyrSi  Якщо у Вас немає питань щодо коду, заапрувте будь ласка, PR

2021-12-27 14:18 UTC, radoshDev approved these changes

2021-12-30 19:00 UTC, merged

2022-01-04 16:39 UTC, MiKolka7 commented on src/components/AppBar/AppBar.js
> +import React from "react";
в `react v17` ці правила можна вимкнути
```
{
    "react/jsx-uses-react": "off",
    "react/react-in-jsx-scope": "off"
}
```
і не імпортити весь час `react`

2022-01-05 12:18 UTC, MiKolka7 commented on .eslintrc.js
> +    "unicorn/throw-new-error": "error",
Не потрібно прописувати всі правила, більшість з них встановлені в конфігурації якщо заекстендити `plugin:unicorn/recommended`